#!/usr/bin/env bash
#loops Best School 10 times with some extra if statements

COUNTER=1
while [ $COUNTER -lt 9 ]
do
	if [ $COUNTER = 4 ]
	then
		echo 'bad luck'
	elif [ $COUNTER = 7 ]
	then
		echo 'good luck'
	fi
		echo 'Best School'
	(( COUNTER+=1 ))
done
