#!/usr/bin/env bash
# UWU HAP

apt-get update
apt-get -y upgrade
apt-get -y install haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
cat <<EOT > /etc/haproxy/haproxy.cfg
defaults
    mode    http
frontend http-in
    bind    *:80
    default_backend servers
backend servers
    balance roundrobin
    server  5540-web-01 15.236.158.71:80 check
    server  5540-web-01 35.180.204.139:80 check
EOT
sudo service haproxy restart
